### ISSUE TITLE
navigator

### ISSUE THREAD

**Issue by ph1ex0n** [tchakabam/FlashDetect#1]
Hello, William!
I try to use your flash-detect module.
This error I've got after "npm install flash-detect" and ">DEBUG=kub.node ./bin/www" on my server:

/home/httpd/mydomain.com/content/html/adserve.njs/kub.node/node_modules/flash-detect/FlashDetect.js:167
        if(navigator.plugins && navigator.plugins.length>0){
           ^
ReferenceError: navigator is not defined
    at /home/httpd/mydomain.com/content/html/adserve.njs/kub.node/node_modules/flash-detect/FlashDetect.js:167:12
    at new FlashDetect (/home/httpd/mydomain.com/content/html/adserve.njs/kub.node/node_modules/flash-detect/FlashDetect.js:198:6)
    at Object.<anonymous> (/home/httpd/mydomain.com/content/html/adserve.njs/kub.node/routes/index.js:12:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/httpd/mydomain.com/content/html/adserve.njs/kub.node/app.js:8:14)

What are you thinking about it?

**Comment by sandinmyjoints** [comment]
Hi, my fork of this repo is actually here: https://github.com/spanishdict/FlashDetect

But to try to answer your question, it looks like you're trying to use FlashDetect on your server. Flash cannot be installed on a server. FlashDetect is meant to run in a web browser, where `navigator` will be defined.

**Comment by ph1ex0n** [comment]
Unfortunately, there is no button issue, I can not write anything there. As
far as I know, the command npm must installs your module on my server. I do
TDS, which is to check for the presence flash player in a browser. I think
that I can apply your module for this task. Or I can not?

2015-01-14 5:19 GMT+05:00 William Bert notifications@github.com:

**Comment by sandinmyjoints** [comment]
npm installs the module on your server. Typically would you then include it in your client-side code bundle, possibly using a tool like [browserify](https://github.com/substack/node-browserify), so you can run it in a browser. There is no `navigator` on the server and no Flash, so it cannot detect anything on the server. :)

**Comment by Bartvds** [comment]
I just send PR #2 so we can use this in webpack and browserify.

**Comment by ph1ex0n** [comment]
.
